# Generated by Django 4.1 on 2022-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
